kind: Service
apiVersion: v1
metadata:
  name: az-node-app
spec:
  selector:
    app: az-node-app
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: httpport
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: az-node-app-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
     - hosts:
       - "blob.fancy.cloud"
       secretName:  tls-fancy
  rules:
  - host: blob.fancy.cloud
    http:
     paths:
     - path: /
       backend:
         serviceName: az-node-app
         servicePort: httpport
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: az-node-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: az-node-app
        tier: frontend
    spec:
      containers:
        - name: az-node-app
          image: fancy.azurecr.io/az-node-app:latest
          env:
          - name: AZURE_STORAGE_CONNECTION_STRING     
            value: "DefaultEndpointsProtocol=https;AccountName=<INSERT>;AccountKey=<INSERT>"
          - name: INSTRUMENTATION_KEY
            value: "<INSERT>"
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
